name: another_harvester_game
description: LDJAM52 game about harvesting

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.5.0
  flame_forge2d: ^0.12.4
  flame_audio: ^1.3.4
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/audio/sounds/
